#!/bin/bash

# Create main bootcamp folder
mkdir Coding-Bootcamp
cd Coding-Bootcamp

# Fall cohort setup
mkdir FallCohort
cd FallCohort
touch carlos.txt emma.txt
cd ..

# Waitlist setup
mkdir Waitlist
cd Waitlist
touch sophia.txt
cd ..

# Winter cohort setup
mkdir WinterCohort
cd WinterCohort
touch alice.txt bob.txt chris.txt

# Create Student backup file
cp bob.txt bob_backup.txt
cd ..

# Move student from waitlist
mv -i Waitlist/sophia.txt WinterCohort/

# Delete a student
rm WinterCohort/chris.txt
